name: Build

on: push

jobs:
  build_job:
    name: Assemble Gradle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      # Access API_KEY
      - name: Decode credentials.properties
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: echo API_KEY=\"$API_KEY\" > ./credentials.properties

      # Build
      - name: Assemble Debug
        run: ./gradlew assembleDebug
