name: Kotlin Lint

on: push

jobs:
  linting-job:
    name: Kt Lint Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Access API_KEY
      - name: Decode credentials.properties
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: echo API_KEY=\"$API_KEY\" > ./credentials.properties

      - name: Ktlint Check
        run: ./gradlew ktlintCheck