name: NewsLand Ci Pipeline

on: push

jobs:
  build_job:
    name: Assemble Gradle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Assemble Debug
        run: ./gradlew assembleDebug

      - name: Ktlint Check
        run: ./gradlew ktlintCheck